const PAGE_SIZE=24;
let properties=[],filtered=[],page=1;
const $=id=>document.getElementById(id);
const normalize=v=>(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const titleCase=v=>(v||"").toLocaleLowerCase("es-MX").replace(/(^|[\s(/-])\p{L}/gu,l=>l.toLocaleUpperCase("es-MX"));
const publicSource=p=>p.sourceKind==="link"?"Propiedad por link":`Pestaña: ${p.inventory}`;
const publicCode=p=>p.sourceKind==="link"?`HS-${p.folio}`:p.folio;
const legalCategory=value=>{const v=normalize(value);if(/escritura|escrituracion|inscripcion|notaria|formaliz/.test(v))return"Escriturada";if(/posesion/.test(v))return"Posesión";if(/adjudic/.test(v))return"Adjudicada";if(/litig|demanda|emplaz|sentencia|remate|juicio|ejecucion|mora/.test(v))return"Litigio";if(/venta normal|compra venta/.test(v))return"Venta directa";return"Otra etapa"};
const iconFor=type=>{const v=normalize(type);return v.includes("terreno")?"◇":v.includes("departamento")?"▦":v.includes("local")||v.includes("comercial")?"▤":v.includes("oficina")?"▥":"⌂"};
const whatsapp=p=>{const msg=`Hola, solicito información de esta propiedad.\nClave/Folio: ${publicCode(p)}\nColonia: ${p.colony}\nMunicipio: ${p.municipality}\nEstado: ${p.state}\nOrigen: ${publicSource(p)}`;return`https://wa.me/523343340062?text=${encodeURIComponent(msg)}`};
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function fillSelect(id,values){$(id).innerHTML+=values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(titleCase(v))}</option>`).join("")}
function fillTypeSelect(values){$("type").innerHTML+=values.map(([key,label])=>`<option value="${escapeHtml(key)}">${escapeHtml(titleCase(label))}</option>`).join("")}
function applyFilters(){const q=normalize($("query").value.trim()),state=$("state").value,type=$("type").value,legal=$("legal").value;filtered=properties.filter(p=>{const text=normalize(`${publicCode(p)} ${p.folio} ${p.colony} ${p.municipality} ${p.state} ${p.type} ${p.legalStage} ${publicSource(p)}`);return(!q||text.includes(q))&&(state==="Todos"||p.state===state)&&(type==="Todos"||normalize(p.type.trim())===type)&&(legal==="Todas"||legalCategory(p.legalStage)===legal)}).sort((a,b)=>{if(!a.state&&b.state)return 1;if(a.state&&!b.state)return-1;return a.state.localeCompare(b.state,"es",{sensitivity:"base"})||a.municipality.localeCompare(b.municipality,"es",{sensitivity:"base"})||a.colony.localeCompare(b.colony,"es",{sensitivity:"base"})||publicCode(a).localeCompare(publicCode(b),"es",{numeric:true,sensitivity:"base"})});page=1;render(false)}
function render(scrollToCatalog=false){const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);$("resultTotal").textContent=filtered.length.toLocaleString("es-MX");$("catalogStatus").hidden=visible.length>0;$("propertyGrid").hidden=!visible.length;$("catalogStatus").innerHTML=visible.length?"":`<strong>No encontramos inmuebles con esos datos.</strong>`;$("propertyGrid").innerHTML=visible.map(p=>`<article class="property-card"><div class="card-top"><span class="property-icon">${iconFor(p.type)}</span><div><span class="folio">${p.sourceKind==="link"?"Clave":"Folio"} ${escapeHtml(publicCode(p))}</span><h3>${escapeHtml(titleCase(p.type))}</h3></div></div><div class="location"><span class="pin">●</span><div><p class="colony">${escapeHtml(titleCase(p.colony))}</p><p>${escapeHtml(titleCase(p.municipality))}${p.state?`, ${escapeHtml(titleCase(p.state))}`:""}</p></div></div><div class="legal"><span>${escapeHtml(legalCategory(p.legalStage))}</span><p>${escapeHtml(p.legalStage)}</p></div><a class="whatsapp" href="${whatsapp(p)}" target="_blank" rel="noreferrer">Solicitar información por WhatsApp</a><div class="card-footer"><span>${escapeHtml(publicSource(p))}</span><span class="${p.availability==="No disponible"?"status muted":"status"}">${escapeHtml(p.availability)}</span></div></article>`).join("");$("pagination").hidden=filtered.length<=PAGE_SIZE;$("pageLabel").textContent=`Página ${page} de ${pages}`;$("previous").disabled=page===1;$("next").disabled=page===pages;if(scrollToCatalog)window.scrollTo({top:document.querySelector(".catalog").offsetTop-20,behavior:"smooth"})}
async function start(){try{let data;if(Array.isArray(window.CATALOG_PROPERTIES))data={properties:window.CATALOG_PROPERTIES};else{const response=await fetch("./properties.json");if(!response.ok)throw new Error();data=await response.json()}properties=data.properties||[];$("heroTotal").textContent=properties.length.toLocaleString("es-MX");const collator=new Intl.Collator("es",{sensitivity:"base"});fillSelect("state",[...new Set(properties.map(p=>p.state).filter(Boolean))].sort(collator.compare));const typeMap=new Map();properties.forEach(p=>{const label=p.type.trim(),key=normalize(label);if(label&&!typeMap.has(key))typeMap.set(key,label)});fillTypeSelect([...typeMap.entries()].sort((a,b)=>collator.compare(a[1],b[1])));filtered=[...properties];applyFilters()}catch{$("catalogStatus").innerHTML="<strong>No fue posible cargar el catálogo.</strong><br>Verifica que properties-data.js esté en la misma carpeta que index.html."}}
$("query").addEventListener("input",()=>{$("state").value="Todos";$("type").value="Todos";$("legal").value="Todas";applyFilters()});["state","type","legal"].forEach(id=>$(id).addEventListener("change",applyFilters));$("previous").addEventListener("click",()=>{page--;render(true)});$("next").addEventListener("click",()=>{page++;render(true)});
$("clearFilters").addEventListener("click",()=>{$("query").value="";$("state").value="Todos";$("type").value="Todos";$("legal").value="Todas";applyFilters();$("query").focus()});
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js?v=4").catch(()=>{});start();
